commitments/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from commitments_site import views


urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(
        r'^$',
        views.ElectionListView.as_view(),
        name='elections'
    ),
    url(
        r'^(?P<slug>[^/]+)/$',
        views.ElectionDetailView.as_view(),
        name='commitments'
    ),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commitments_site/models.py
from django.db import models

from fontawesome.fields import IconField


class Election(models.Model):
    name = models.CharField(
        max_length=50,
        help_text='The name of the election'
    )

    slug = models.SlugField(
        help_text="The election's slug."
    )

    logo = models.ImageField(
        help_text="The logo of the entity for which this election was held.",
        blank=True
    )

    results = models.URLField(
        blank=True,
        help_text="The election's results URL, if any."
    )

    start_date = models.DateField(
        blank=True,
        help_text='The official date that the election started.'
    )

    end_date = models.DateField(
        blank=True,
        help_text='The official date that the election ended.'
    )

    participants = models.ManyToManyField(
        'commitments_site.Party',
        help_text='A list of participants in this election.'
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['end_date']


class Party(models.Model):
    name = models.CharField(
        unique=True,
        max_length=50,
        help_text='The name of the party.'
    )

    slug = models.SlugField(
        help_text="The party's slug."
    )

    website = models.URLField(
        blank=True,
        help_text='The party\'s website, if any.'
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'parties'


class Commitment(models.Model):
    UNACTIONED = 'UA'
    IMPLEMENTED = 'IM'
    FAILED = 'FA'
    IN_PROGRESS = 'PR'

    STATUS_CHOICES = (
        (UNACTIONED, 'No action taken'),
        (IMPLEMENTED, 'Implemented'),
        (FAILED, 'Failed'),
        (IN_PROGRESS, 'In progress'),
    )

    name = models.CharField(
        max_length=100,
        help_text='A short name for the commitment.',
    )

    slug = models.SlugField(
        help_text="The commitment's slug."
    )

    description = models.TextField(
        help_text='A more in-depth description of the commitment.'
    )

    icon = IconField(
        help_text='An icon to distinguish the commitment.'
    )

    status = models.CharField(
        max_length=2,
        help_text='The status of the commitment',
        choices=STATUS_CHOICES
    )

    status_description = models.TextField(
        blank=True,
        help_text='A commitment-specific description of the current status'
                  ', if any.',
    )

    party = models.ForeignKey(
        'commitments_site.Party',
        help_text='The party that made this commitment.'
    )

    elections = models.ManyToManyField(
        'commitments_site.Election',
        help_text='The election(s) this promise was made at.',
    )

    class Meta:
        unique_together = ['name', 'party']
        ordering = ['name']

    def __str__(self):
        return "{s.name} ({s.party})".format(s=self)

commitments_site/views.py
from django.views import generic
from django import shortcuts
import models


class ElectionListView(generic.ListView):
    model = models.Election
    template_name = 'election_list.html'


class ElectionDetailView(generic.TemplateView):
    model = models.Election
    template_name = 'commitments.html'
    slug_field = 'slug'

    def get_context_data(self, *args, **kwargs):
        c = super(ElectionDetailView, self).get_context_data(*args, **kwargs)
        c['election'] = shortcuts.get_object_or_404(
            models.Election, slug=kwargs['slug'])
        c['parties'] = [{
            'party': p,
            'implemented': models.Commitment.objects.filter(
                party=p,
                elections=c['election'],
                status=models.Commitment.IMPLEMENTED
            ),
            'commitments': models.Commitment.objects.filter(
                party=p,
                elections=c['election']
            ),
        } for p in c['election'].participants.all()]
        return c

commitments_site/templates/commitments.html
{% extends "base.html" %}

{% load fontawesome %}

{% block site_title %}{{ election.name }}{% endblock %}
{% block body_title %}{{ election.name }}{% endblock %}

{% block custom_head %}
    <meta property='og:description' content='Election commitment tracker for {{ election.name }}. What has your vote done for you?' />
    {% if election.logo %}
        <meta property='og:image' content='http://commitments.kye.id.au/{{ election.logo.url }}' />
    {% endif %}
{% endblock %}

{% block content %}

<h2>General Information</h2>
<table class="table">
    <tr>
        <th>Name</td>
        <td>{{ election.name }}</td>
    </tr>
    {% if election.results %}
        <tr>
            <th>Results</td>
            <td><a href="{{ election.results }}">{{ election.results }}</a></td>
        </tr>
    {% endif %}
    <tr>
        <th>Start Date</td>
        <td>{{ election.start_date }}</td>
    </tr>
    <tr>
        <th>End Date</td>
        <td>{{ election.end_date }}</td>
    </tr>
    {% if election.participants.all %}
        <tr>
            <th>Participants</td>
            <td>{{ election.participants.all|join:', ' }}</td>
        </tr>
    {% endif %}
</table>

<!--<h2>Key</h2>
<table class="table">
    <tr>
        <td>
            <span class='label label-warning'>Unactioned</span>
        </td>
        <td>
            There is no evidence that any effort has been made toward the implementation of this commitment.
        </td>
    </tr>
    <tr>
        <td>
            <span class='label label-danger'>Failed</span>
        </td>
        <td>
            There has been a visible failure in the implementation of this commitment.
        </td>
    </tr>
    <tr>
        <td>
            <span class='label label-primary'>In Progress</span>
        </td>
        <td>
            Visible progress has been made toward the implementation of this commitment.
        </td>
    </tr>
    <tr>
        <td>
            <span class='label label-success'>Implemented</span>
        </td>
        <td>
            This commitment has been implemented in full.
        </td>
    </tr>
</table>-->

{% for p_info in parties %}
    <h2 id='{{ p_info.party.slug }}'><a href="#{{ p_info.party.slug }}">{{ p_info.party }}</a></h2>
    {% if p_info.commitments %}
        <table class="table table-condensed">
            <tr>
                <td class="col-md-3">Commitments made</td>
                <td>{{ p_info.commitments.count }}</td>
            </tr>
            <tr>
                <td class="col-md-3">Commitments implemented</td>
                <td>{{ p_info.implemented.count }}</td>
            </tr>
        </table>

        {% for commitment in p_info.commitments %}
            <div class="panel panel-default" id='{{ commitment.party.slug }}-{{ commitment.slug }}'>
                <div class="panel-heading">
                    <h3 class="panel-title">
                        {{ commitment.icon.as_html }}
                        {{ commitment.name }}
                        {% if commitment.status == 'UA' %}
                            <span class='label label-warning'>Unactioned</span>
                        {% elif commitment.status == 'IM' %}
                            <span class='label label-success'>Implemented</span>
                        {% elif commitment.status == 'FA' %}
                            <span class='label label-danger'>Failed</span>
                        {% elif commitment.status == 'PR' %}
                            <span class='label label-primary'>In Progress</span>
                        {% endif %}
                    </h3>
                </div>
                <div class="panel-body">
                    <p>{{ commitment.description|linebreaks }}</p>
                    <hr />
                    {% if commitment.status_description %}
                        <p>{{ commitment.status_description|linebreaks }}</p>
                    {% else %}
                        <p class='text-danger'>There is no status description for this commitment.</p>
                    {% endif %}
                </div>
                <div class="panel-footer">
                    <a href="#{{ commitment.party.slug }}-{{ commitment.slug }}">
                        {% fontawesome_icon 'link' %}
                    </a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h4 class="text-danger">{{ p_info.party }} didn't make any commitments.</h4>
    {% endif %}
{% endfor %}

{% endblock %}

commitments_site/templates/election_list.html
{% extends "base.html" %}

{% block site_title %}Elections{% endblock %}
{% block body_title %}Elections{% endblock %}

{% block content %}
{% if object_list %}
    <table class="table">
        <thead>
            <th>Name</th>
            <th>Participants</th>
            <th class="col-md-3"></th>
        </thead>
        <tbody>
            {% for election in object_list %}
            <tr>
                <td>
                    {{ election.name }}<br />
                    <small>{{ election.start_date|date }}
                    {% if election.end_date != election.start_date %}
                        to {{ election.end_date|date }}
                    {% endif %}</small>
                </td>
                <td>
                    {{ election.participants.all|join:', ' }}
                </td>
                <td>
                    <a href="{{ election.results }}" class="btn {% if not election.results %}disabled{% endif %} btn-primary">Results</a>
                    <a href="{% url 'commitments' election.slug %}" class="btn {% if not election.commitment_set.all %}disabled{% endif %} btn-success">Commitments</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p class="text-danger">There are no elections!</p>
    <p class="text-danger">Democracy is over!</p>
{% endif %}
{% endblock %}

templates/base.html
{% load bootstrap3 %}
{% load staticfiles %}
{% load fontawesome %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block site_title %}Example{% endblock %} - commitments</title>

    <meta property='og:site_name' content='commitments' />

    {% block custom_head %}
    {% endblock %}
    
    {% bootstrap_css %}
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
    {% fontawesome_stylesheet %}

    <!-- <link rel="icon" type="image/png" href="{% static 'img/coderdojo_logo_small.png' %}" /> -->

    <!-- Page-specific CSS -->
    {% block custom_css %}
    {% endblock %}
</head>
<body>
<div id="wrap">
    <div class="container">
        <nav id="navbar" class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand">
                        <span id="brand_text">commitments</span>
                        <img class="hidden" src="{% static 'img/comssa_logo_128.png' %}" id="brand_logo" />
                    </a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'elections' %}">Elections</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div><!--/.container-fluid -->
        </nav>
    </div>
    
    <div class="container">

        <div class="page-header">
            <h1>
                {% block body_title %}Example{% endblock %}
            </h1>
        </div>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
            <hr />
        {% endif %}
        {% block content %}
            <p>This needs to be changed.</p>
        {% endblock %}
    </div>
    <div id="push"></div>
</div>

    <div id="footer">
        <div class="container">
            <p id="footer_credits" class="text-muted credit text-center">
                commitments &copy; 2015 <a href="https://kye.id.au">Kye Russell</a>.<br />
                Created independently by Kye Russell. This website is not affiliated with any third-parties.<br />
                This project is open-source! It's <a href="https://bitbucket.org/kyer/commitments/">available on BitBucket</a>.
            </p>
        </div>
    </div>

    <script src="{% bootstrap_jquery_url %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/csrf.js' %}"></script>
    {% bootstrap_javascript %}

    <!-- Page-specific Javascript -->
    {% block custom_js %}
    {% endblock %}

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-61158331-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>